In [ ]:
# This notebook applies the following basic Machine Learning models:
# Logistic Regression, SVM, KNN and Decision Trees
###

# 0. Preparation
###
# Importing libraries
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2

from sklearn.metrics import classification_report, f1_score
from sklearn import linear_model, preprocessing
from sklearn.model_selection import train_test_split
from sklearn import svm, neighbors

In [ ]:
# Mounting GoogleDrive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Reading data file from GoogleDrive
df = pd.read_pickle("/content/drive/My Drive/Data Science/Team Project X-Rays/Dataframes/df_basic_1.0.pkl")
df.head()

# Define data name
df_name = "Baseline 1.0"

# Define random subsample for computation efficiency
#df = df.sample(500)

In [ ]:
# Explore Data
###

# Check data type is DataFrame
print(type(df))

# Show dimensions
print(df.shape)

# Show labels
print(df.Case.value_counts())

# Check distributions after normalisation
df.describe()

# => we can see that distributions of pixels are normed between 0 and 1 and the variances are similar

<class 'pandas.core.frame.DataFrame'>
(21105, 4098)
Case
Normal             10191
Lung_Opacity        6012
COVID               3564
Viral Pneumonia     1338
Name: count, dtype: int64

,PX_1,PX_2,PX_3,PX_4,PX_5,PX_6,PX_7,PX_8,PX_9,PX_10,...,PX_4087,PX_4088,PX_4089,PX_4090,PX_4091,PX_4092,PX_4093,PX_4094,PX_4095,PX_4096
count,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,...,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000,21105.000000
mean,0.167560,0.132034,0.131165,0.135850,0.140324,0.145023,0.148924,0.151930,0.155404,0.158815,...,0.583761,0.543275,0.497499,0.448384,0.394900,0.342358,0.295952,0.256192,0.229832,0.236831
std,0.240803,0.208924,0.205242,0.205556,0.206621,0.207949,0.210028,0.211958,0.213880,0.216116,...,0.271012,0.283928,0.295691,0.303905,0.307331,0.306647,0.300506,0.290565,0.280255,0.284174
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.007843,0.003922,0.003922,0.007843,0.007843,0.007843,0.007843,0.007843,0.007843,0.007843,...,0.454902,0.368627,0.247059,0.125490,0.062745,0.035294,0.023529,0.011765,0.007843,0.007843
50%,0.047059,0.035294,0.031373,0.035294,0.039216,0.039216,0.043137,0.043137,0.047059,0.047059,...,0.654902,0.615686,0.564706,0.501961,0.407843,0.286275,0.172549,0.101961,0.078431,0.090196
75%,0.227451,0.152941,0.156863,0.176471,0.196078,0.215686,0.227451,0.235294,0.247059,0.250980,...,0.784314,0.760784,0.737255,0.705882,0.666667,0.615686,0.552941,0.478431,0.411765,0.419608
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
# 1. Data preprocessing
###

# Create categorical variable from Case
df["Case"] = df.Case.replace({"Normal": 0, "COVID": 1, "Lung_Opacity": 2, "Viral Pneumonia": 3})
df.Case.astype(int)

# Check construction
print(df.Case.value_counts())

# Split data into target and features
target = df.Case

# Features data: Drop Names and target
data = df.drop(["Name", "Case"], axis = 1)
data.head()
data.shape

# Split data into training and Test sets, save random state
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size = 0.2, random_state = 123)

Case
0    10191
2     6012
1     3564
3     1338
Name: count, dtype: int64

In [ ]:
# 2. Model 1 - Logistic Regression
###
import time
start_time = time.time()

# Instantiate Logistic regression for classification
clf1_name = "Logistic Regression"
clf1 = linear_model.LogisticRegression(solver='lbfgs', C = 1.0, max_iter = 10000)

# Train the model on training data
clf1.fit(X_train, y_train)

# Make predictions on test set
y_pred = clf1.predict(X_test)

# Calc accuracys
clf1_score = clf1.score(X_test, y_test)

# Calc mean unweighted F1 Score in all classes
clf1_f1 = f1_score(y_test, y_pred, average = "macro")

# Measure time
model1_time = (time.time() - start_time)/60

In [ ]:
# Show Results
###

# Modelling Time
print("Model 1: --- %s minutes ---" % model1_time)

# Score and F1-Score
print("The score is:", clf1_score)
print("The mean F1-Score (unweighted) is:", clf1_f1)

# Show Confusion Matrix
cm1 = pd.crosstab(y_test, y_pred, rownames = ['Realised Class'], colnames = ['Predicted Class'])
display(cm1)

# Show classification report
model1_cr = classification_report(y_test, y_pred)
print(model1_cr)

Model 1: --- 27.98339457909266 minutes ---
The score is: 0.7199715707178393
The mean F1-Score (unweighted) is: 0.7183597328889032

Predicted Class     0    1    2    3
Realised Class
0                1697  150  217   39
1                 183  361  131    6
2                 272  120  758   15
3                  14   19   16  223

              precision    recall  f1-score   support

           0       0.78      0.81      0.80      2103
           1       0.56      0.53      0.54       681
           2       0.68      0.65      0.66      1165
           3       0.79      0.82      0.80       272

    accuracy                           0.72      4221
   macro avg       0.70      0.70      0.70      4221
weighted avg       0.72      0.72      0.72      4221

In [ ]:
# 3. Model 2 - linear SVM
###
import time
start_time = time.time()

# Instantiate SVM
clf2_name = "linear SVM"
clf2 = svm.SVC(gamma = 0.01, kernel = "poly")

# Train the model on training data
clf2.fit(X_train, y_train)

# Make predictions on test set
y_pred = clf2.predict(X_test)

# Calc accuracy
clf2_score = clf2.score(X_test, y_test)

# Calc mean unweighted F1 Score in all classes
clf2_f1 = f1_score(y_test, y_pred, average = "macro")

# Measure time
model2_time = (time.time() - start_time)/60

In [ ]:
# Show Results
###

# Modelling Time
print("Model 2: --- %s minutes ---" % model2_time)

# Score and F1-Score
print("The score is:", clf2_score)
print("The mean F1-Score (unweighted) is:", clf2_f1)

# Show Confusion Matrix
cm2 = pd.crosstab(y_test, y_pred, rownames = ['Realised Class'], colnames = ['Predicted Class'])
display(cm2)

# Show classification report
model2_cr = classification_report(y_test, y_pred)
print(model2_cr)

Model 2: --- 17.158799743652345 minutes ---
The score is: 0.8005212035062781
The mean F1-Score (unweighted) is: 0.8003937699139198

Predicted Class     0    1    2    3
Realised Class
0                1776  105  202   20
1                 120  481   79    1
2                 205   73  883    4
3                  19    4   10  239

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      2103
           1       0.73      0.71      0.72       681
           2       0.75      0.76      0.76      1165
           3       0.91      0.88      0.89       272

    accuracy                           0.80      4221
   macro avg       0.81      0.80      0.80      4221
weighted avg       0.80      0.80      0.80      4221

In [ ]:
# 3. Model 3 - KNN
###
from sklearn import neighbors
import time
start_time = time.time()

# Instantiate classifier
clf3_name = "KNN"
clf3 = neighbors.KNeighborsClassifier(n_neighbors = 7, metric = 'minkowski')

# Train the model on training data
clf3.fit(X_train, y_train)

# Make predictions on test set
y_pred = clf3.predict(X_test)

# Calc accuracys
clf3_score = clf3.score(X_test, y_test)

# Calc mean unweighted F1 Score in all classes
clf3_f1 = f1_score(y_test, y_pred, average = "macro")

# Measure time
model3_time = (time.time() - start_time)/60

In [ ]:
# Show Results
###

# Modelling Time
print("Model 3: --- %s minutes ---" % model3_time)

# Score and F1-Score
print("The score is:", clf3_score)
print("The mean F1-Score (unweighted) is:", clf3_f1)

# Show Confusion Matrix
cm3 = pd.crosstab(y_test, y_pred, rownames = ['Realised Class'], colnames = ['Predicted Class'])
display(cm3)

# Show classification report
model3_cr = classification_report(y_test, y_pred)
print(model3_cr)

Model 3: --- 0.8627974033355713 minutes ---
The score is: 0.7865434731106373
The mean F1-Score (unweighted) is: 0.7833893069036977

Predicted Class     0    1    2    3
Realised Class
0                1840   77  161   25
1                 142  411  121    7
2                 253   77  828    7
3                  17    4   10  241

              precision    recall  f1-score   support

           0       0.82      0.87      0.85      2103
           1       0.72      0.60      0.66       681
           2       0.74      0.71      0.72      1165
           3       0.86      0.89      0.87       272

    accuracy                           0.79      4221
   macro avg       0.78      0.77      0.78      4221
weighted avg       0.78      0.79      0.78      4221

In [ ]:
# 3. Model 4 - Decision Tree
###
from sklearn.tree import DecisionTreeClassifier
import time
start_time = time.time()

# Instantiate classifier
clf4_name = "Decision Tree"
clf4 = DecisionTreeClassifier(criterion = "entropy", max_depth = 4, random_state = 123)

# Train the model on training data
clf4.fit(X_train, y_train)

# Make predictions on test set
y_pred = clf4.predict(X_test)

# Calc accuracys
clf4_score = clf4.score(X_test, y_test)

# Calc mean unweighted F1 Score in all classes
clf4_f1 = f1_score(y_test, y_pred, average = "macro")

# Measure time
model4_time = (time.time() - start_time)/60

In [ ]:
# Show Results
###

# Modelling Time
print("Model 4: --- %s minutes ---" % model4_time)

# Score and F1-Score
print("The score is:", clf4_score)
print("The mean F1-Score (unweighted) is:", clf4_f1)

# Show Confusion Matrix
cm4 = pd.crosstab(y_test, y_pred, rownames = ['Realised Class'], colnames = ['Predicted Class'])
display(cm4)

# Show classification report
model4_cr = classification_report(y_test, y_pred)
print(model4_cr)
# Ideas: Could show most important Features here. But well, there are 4000 pixels...

Model 4: --- 0.32833014726638793 minutes ---
The score is: 0.6531627576403696
The mean F1-Score (unweighted) is: 0.6420923914434264

Predicted Class     0    1    2    3
Realised Class
0                1739   87  231   46
1                 250  268  150   13
2                 419  110  613   23
3                  57   20   58  137

              precision    recall  f1-score   support

           0       0.71      0.83      0.76      2103
           1       0.55      0.39      0.46       681
           2       0.58      0.53      0.55      1165
           3       0.63      0.50      0.56       272

    accuracy                           0.65      4221
   macro avg       0.62      0.56      0.58      4221
weighted avg       0.64      0.65      0.64      4221